package tier3.db.corba;


/**
* tier3/db/corba/ItemDatabase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from database.idl
* Monday, 8 December 2014 10:18:02 o'clock CET
*/

public interface ItemDatabase extends ItemDatabaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ItemDatabase
