package tier3.db.corba;


/**
* tier3/db/corba/ItemDatabasePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from database.idl
* Monday, 8 December 2014 10:18:02 o'clock CET
*/

public abstract class ItemDatabasePOA extends org.omg.PortableServer.Servant
 implements tier3.db.corba.ItemDatabaseOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getLocations", new java.lang.Integer (0));
    _methods.put ("stored", new java.lang.Integer (1));
    _methods.put ("countItems", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // tier3/db/corba/ItemDatabase/getLocations
       {
         int id = in.read_long ();
         int amount = in.read_long ();
         String $result[] = null;
         $result = this.getLocations (id, amount);
         out = $rh.createReply();
         tier3.db.corba.ItemDatabasePackage.StrArrHelper.write (out, $result);
         break;
       }

       case 1:  // tier3/db/corba/ItemDatabase/stored
       {
         int id = in.read_long ();
         int amount = in.read_long ();
         String location = in.read_string ();
         boolean $result = false;
         $result = this.stored (id, amount, location);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // tier3/db/corba/ItemDatabase/countItems
       {
         int id = in.read_long ();
         String location = in.read_string ();
         int $result = (int)0;
         $result = this.countItems (id, location);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:tier3/db/corba/ItemDatabase:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ItemDatabase _this() 
  {
    return ItemDatabaseHelper.narrow(
    super._this_object());
  }

  public ItemDatabase _this(org.omg.CORBA.ORB orb) 
  {
    return ItemDatabaseHelper.narrow(
    super._this_object(orb));
  }


} // class ItemDatabasePOA
