package tier3.db.corba;


/**
* tier3/db/corba/ItemDatabaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from database.idl
* Monday, 8 December 2014 10:18:02 o'clock CET
*/

public interface ItemDatabaseOperations 
{
  String[] getLocations (int id, int amount);
  boolean stored (int id, int amount, String location);
  int countItems (int id, String location);
} // interface ItemDatabaseOperations
