package tier3.db.corba;


/**
* tier3/db/corba/ItemDatabaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from database.idl
* Monday, 8 December 2014 10:18:02 o'clock CET
*/

abstract public class ItemDatabaseHelper
{
  private static String  _id = "IDL:tier3/db/corba/ItemDatabase:1.0";

  public static void insert (org.omg.CORBA.Any a, tier3.db.corba.ItemDatabase that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static tier3.db.corba.ItemDatabase extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (tier3.db.corba.ItemDatabaseHelper.id (), "ItemDatabase");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static tier3.db.corba.ItemDatabase read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ItemDatabaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, tier3.db.corba.ItemDatabase value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static tier3.db.corba.ItemDatabase narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof tier3.db.corba.ItemDatabase)
      return (tier3.db.corba.ItemDatabase)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      tier3.db.corba._ItemDatabaseStub stub = new tier3.db.corba._ItemDatabaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static tier3.db.corba.ItemDatabase unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof tier3.db.corba.ItemDatabase)
      return (tier3.db.corba.ItemDatabase)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      tier3.db.corba._ItemDatabaseStub stub = new tier3.db.corba._ItemDatabaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
