package tier3.db.corba.ItemDatabasePackage;


/**
* tier3/db/corba/ItemDatabasePackage/StrArrHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from database.idl
* Monday, 8 December 2014 10:18:02 o'clock CET
*/

public final class StrArrHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StrArrHolder ()
  {
  }

  public StrArrHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = tier3.db.corba.ItemDatabasePackage.StrArrHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    tier3.db.corba.ItemDatabasePackage.StrArrHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return tier3.db.corba.ItemDatabasePackage.StrArrHelper.type ();
  }

}
